const lang = {
  english: {
    search: "Search",
    gptSearchBarPlaceholder: "What would you like to watch today?",
    gptSearchText: "GPT Search",
    startWatchingText: "Start Watching",
    signOut: "Sign Out",
    playButtonText: "Play",
    moreInfoText: "More Info",
    nowPlayingText: "Now Playing",
    topRatedText: "Top Rated",
    popularText: "Popular",
    upcomingText: "Upcoming",
    movieTitleText: "Avatar: Fire and Ash",
    movieOverviewText:
      "In the wake of the devastating war against the RDA and the loss of their eldest son, Jake Sully and Neytiri face a new threat on Pandora: the Ash People, a violent and power-hungry Na'vi tribe led by the ruthless Varang. Jake's family must fight for their survival and the future of Pandora in a conflict that pushes them to their emotional and physical limits.",
    signInText: "Sign In",
    signUpText: "Sign Up",
    fullnameText: "Full Name",
    emailText: "Email Address",
    passwordText: "Password",
    newToNetflixText: "New To Netflix?",
    alreadyRegisteredText: "Already Registered?",
    signInNowText: "Sign In Now",
    signUpNowText: "Sign Up Now",
  },

  hindi: {
    search: "खोज",
    gptSearchBarPlaceholder: "आज आप क्या देखना चाहेंगे?",
    gptSearchText: "GPT खोज",
    startWatchingText: "देखना शुरू करें",
    signOut: "साइन आउट",
    playButtonText: "चलाएं",
    moreInfoText: "और जानकारी",
    nowPlayingText: "अभी चल रहा है",
    topRatedText: "शीर्ष रेटेड",
    popularText: "लोकप्रिय",
    upcomingText: "आगामी",
    movieTitleText: "अवतार: फायर एंड ऐश",
    movieOverviewText:
      "RDA के खिलाफ विनाशकारी युद्ध और अपने सबसे बड़े बेटे की मृत्यु के बाद, जेक सुली और नेयतिरी पैंडोरा पर एक नए खतरे का सामना करते हैं: ऐश पीपल, एक हिंसक और सत्ता-लोलुप ना'वी जनजाति, जिसका नेतृत्व निर्दयी वरंग करता है। जेक के परिवार को अपने अस्तित्व और पैंडोरा के भविष्य के लिए लड़ना होगा।",
    signInText: "साइन इन",
    signUpText: "साइन अप",
    fullnameText: "पूरा नाम",
    emailText: "ईमेल पता",
    passwordText: "पासवर्ड",
    newToNetflixText: "नेटफ्लिक्स पर नए हैं?",
    alreadyRegisteredText: "पहले से पंजीकृत हैं?",
    signInNowText: "अभी साइन इन करें",
    signUpNowText: "अभी साइन अप करें",
  },

  gujarati: {
    search: "શોધો",
    gptSearchBarPlaceholder: "આજે તમે શું જોવા માંગો છો?",
    gptSearchText: "GPT શોધ",
    startWatchingText: "જુઓ શરૂ કરો",
    signOut: "સાઇન આઉટ",
    playButtonText: "ચાલુ કરો",
    moreInfoText: "વધુ માહિતી",
    nowPlayingText: "હમણાં ચાલી રહ્યું છે",
    topRatedText: "ટોચના રેટેડ",
    popularText: "લોકપ્રિય",
    upcomingText: "આગામી",
    movieTitleText: "અવતાર: ફાયર એન્ડ ઍશ",
    movieOverviewText:
      "RDA સામેના વિનાશક યુદ્ધ અને તેમના મોટાભાઈના મૃત્યુ પછી, જેક સુલી અને નેતિયરી પેન્ડોરા પર નવા ખતરા સામે ઊભા રહે છે: ઍશ પિપલ, એક હિંસક અને શક્તિ લોલુપ ના'વી જનજાતિ. જેકનું પરિવાર પોતાના અસ્તિત્વ અને પેન્ડોરાના ભવિષ્ય માટે લડે છે.",
    signInText: "સાઇન ઇન",
    signUpText: "સાઇન અપ",
    fullnameText: "પૂર્ણ નામ",
    emailText: "ઇમેલ સરનામું",
    passwordText: "પાસવર્ડ",
    newToNetflixText: "નેટફ્લિક્સમાં નવા છો?",
    alreadyRegisteredText: "પહેલેથી નોંધાયેલા છો?",
    signInNowText: "હમણાં સાઇન ઇન કરો",
    signUpNowText: "હમણાં સાઇન અપ કરો",
  },

  bengali: {
    search: "অনুসন্ধান",
    gptSearchBarPlaceholder: "আজ আপনি কী দেখতে চান?",
    gptSearchText: "GPT অনুসন্ধান",
    startWatchingText: "দেখা শুরু করুন",
    signOut: "সাইন আউট",
    playButtonText: "প্লে",
    moreInfoText: "আরও তথ্য",
    nowPlayingText: "এখন চলছে",
    topRatedText: "সর্বোচ্চ রেটেড",
    popularText: "জনপ্রিয়",
    upcomingText: "আসন্ন",
    movieTitleText: "অ্যাভাটার: ফায়ার অ্যান্ড অ্যাশ",
    movieOverviewText:
      "RDA-র বিরুদ্ধে বিধ্বংসী যুদ্ধ এবং বড় ছেলের মৃত্যু পর জেক সুলি ও নেইতিরি প্যান্ডোরায় এক নতুন হুমকির মুখোমুখি হয়: অ্যাশ পিপল। এই সংঘর্ষে তাদের পরিবার ও প্যান্ডোরার ভবিষ্যৎ ঝুঁকির মুখে পড়ে।",
    signInText: "সাইন ইন",
    signUpText: "সাইন আপ",
    fullnameText: "পূর্ণ নাম",
    emailText: "ইমেল ঠিকানা",
    passwordText: "পাসওয়ার্ড",
    newToNetflixText: "নেটফ্লিক্সে নতুন?",
    alreadyRegisteredText: "ইতিমধ্যে নিবন্ধিত?",
    signInNowText: "এখনই সাইন ইন করুন",
    signUpNowText: "এখনই সাইন আপ করুন",
  },

  telugu: {
    search: "వెతకండి",
    gptSearchBarPlaceholder: "ఈ రోజు మీరు ఏమి చూడాలనుకుంటున్నారు?",
    gptSearchText: "GPT శోధన",
    startWatchingText: "చూడడం ప్రారంభించండి",
    signOut: "సైన్ అవుట్",
    playButtonText: "ప్లే",
    moreInfoText: "మరిన్ని వివరాలు",
    nowPlayingText: "ప్రస్తుతం ప్రదర్శనలో ఉంది",
    topRatedText: "అత్యుత్తమ రేటింగ్",
    popularText: "ప్రాచుర్యం పొందినవి",
    upcomingText: "రాబోయేవి",
    movieTitleText: "అవతార్: ఫైర్ అండ్ ఆష్",
    movieOverviewText:
      "RDAతో జరిగిన ఘోర యుద్ధం తరువాత, తమ పెద్ద కుమారుని కోల్పోయిన జేక్ సల్లి మరియు నెయ్‌తిరి పాండోరాలో కొత్త ప్రమాదాన్ని ఎదుర్కొంటారు. తమ కుటుంబం మరియు పాండోరా భవిష్యత్తు కోసం పోరాడాల్సి వస్తుంది.",
    signInText: "సైన్ ఇన్",
    signUpText: "సైన్ అప్",
    fullnameText: "పూర్తి పేరు",
    emailText: "ఈమెయిల్ చిరునామా",
    passwordText: "పాస్‌వర్డ్",
    newToNetflixText: "నెట్‌ఫ్లిక్స్‌కు కొత్తవారా?",
    alreadyRegisteredText: "ఇప్పటికే నమోదు అయ్యారా?",
    signInNowText: "ఇప్పుడే సైన్ ఇన్ చేయండి",
    signUpNowText: "ఇప్పుడే సైన్ అప్ చేయండి",
  },

  punjabi: {
    search: "ਖੋਜੋ",
    gptSearchBarPlaceholder: "ਅੱਜ ਤੁਸੀਂ ਕੀ ਦੇਖਣਾ ਚਾਹੁੰਦੇ ਹੋ?",
    gptSearchText: "GPT ਖੋਜ",
    startWatchingText: "ਦੇਖਣਾ ਸ਼ੁਰੂ ਕਰੋ",
    signOut: "ਸਾਈਨ ਆਉਟ",
    playButtonText: "ਚਲਾਓ",
    moreInfoText: "ਹੋਰ ਜਾਣਕਾਰੀ",
    nowPlayingText: "ਹੁਣ ਚੱਲ ਰਿਹਾ ਹੈ",
    topRatedText: "ਟੌਪ ਰੇਟਡ",
    popularText: "ਲੋਕਪ੍ਰਿਯ",
    upcomingText: "ਆਉਣ ਵਾਲੇ",
    movieTitleText: "ਅਵਤਾਰ: ਫਾਇਰ ਐਂਡ ਐਸ਼",
    movieOverviewText:
      "RDA ਦੇ ਖ਼ਿਲਾਫ਼ ਭਿਆਨਕ ਜੰਗ ਤੋਂ ਬਾਅਦ ਅਤੇ ਆਪਣੇ ਵੱਡੇ ਪੁੱਤਰ ਦੀ ਮੌਤ ਮਗਰੋਂ, ਜੇਕ ਸੱਲੀ ਅਤੇ ਨੇਇਤਿਰੀ ਪੈਂਡੋਰਾ ‘ਤੇ ਨਵੇਂ ਖ਼ਤਰੇ ਦਾ ਸਾਹਮਣਾ ਕਰਦੇ ਹਨ। ਆਪਣੇ ਪਰਿਵਾਰ ਅਤੇ ਪੈਂਡੋਰਾ ਦੇ ਭਵਿੱਖ ਲਈ ਲੜਾਈ ਕਰਨੀ ਪੈਂਦੀ ਹੈ।",
    signInText: "ਸਾਈਨ ਇਨ",
    signUpText: "ਸਾਈਨ ਅਪ",
    fullnameText: "ਪੂਰਾ ਨਾਮ",
    emailText: "ਈਮੇਲ ਪਤਾ",
    passwordText: "ਪਾਸਵਰਡ",
    newToNetflixText: "ਨੈਟਫ਼ਲਿਕਸ ‘ਤੇ ਨਵੇਂ ਹੋ?",
    alreadyRegisteredText: "ਪਹਿਲਾਂ ਤੋਂ ਰਜਿਸਟਰਡ?",
    signInNowText: "ਹੁਣੇ ਸਾਈਨ ਇਨ ਕਰੋ",
    signUpNowText: "ਹੁਣੇ ਸਾਈਨ ਅਪ ਕਰੋ",
  },

  spanish: {
    search: "Buscar",
    gptSearchBarPlaceholder: "¿Qué te gustaría ver hoy?",
    gptSearchText: "Búsqueda GPT",
    startWatchingText: "Comenzar a ver",
    signOut: "Cerrar sesión",
    playButtonText: "Reproducir",
    moreInfoText: "Más información",
    nowPlayingText: "En reproducción",
    topRatedText: "Mejor valoradas",
    popularText: "Populares",
    upcomingText: "Próximamente",
    movieTitleText: "Avatar: Fuego y Ceniza",
    movieOverviewText:
      "Tras la devastadora guerra contra la RDA y la pérdida de su hijo mayor, Jake Sully y Neytiri enfrentan una nueva amenaza en Pandora: el Pueblo de las Cenizas. La familia debe luchar por su supervivencia y el futuro de Pandora.",
    signInText: "Iniciar sesión",
    signUpText: "Registrarse",
    fullnameText: "Nombre completo",
    emailText: "Correo electrónico",
    passwordText: "Contraseña",
    newToNetflixText: "¿Nuevo en Netflix?",
    alreadyRegisteredText: "¿Ya registrado?",
    signInNowText: "Inicia sesión ahora",
    signUpNowText: "Regístrate ahora",
  },

  russian: {
    search: "Поиск",
    gptSearchBarPlaceholder: "Что бы вы хотели посмотреть сегодня?",
    gptSearchText: "Поиск GPT",
    startWatchingText: "Начать просмотр",
    signOut: "Выйти",
    playButtonText: "Смотреть",
    moreInfoText: "Подробнее",
    nowPlayingText: "Сейчас в эфире",
    topRatedText: "Лучшие",
    popularText: "Популярные",
    upcomingText: "Скоро",
    movieTitleText: "Аватар: Огонь и Пепел",
    movieOverviewText:
      "После разрушительной войны с RDA и потери старшего сына Джейк Салли и Нейтири сталкиваются с новой угрозой на Пандоре — Народом Пепла. Семья борется за выживание и будущее Пандоры.",
    signInText: "Войти",
    signUpText: "Зарегистрироваться",
    fullnameText: "Полное имя",
    emailText: "Адрес электронной почты",
    passwordText: "Пароль",
    newToNetflixText: "Впервые на Netflix?",
    alreadyRegisteredText: "Уже зарегистрированы?",
    signInNowText: "Войти сейчас",
    signUpNowText: "Зарегистрироваться сейчас",
  },
};

export default lang;
